api_platform:
    resource: .
    type: api_platform
    prefix: /api

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation
    
security_controller:
    resource: '../../src/Controller/SecurityController.php'
    type: annotation

default_controller:
    resource: '../../src/Controller/DefaultController.php'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
